name: "Download and publish test coverage"
description: "Downloads test coverage stats from the base branch, publishes a comment with a summary"
runs:
  using: "composite"
  steps:
    # Strips forward slashes and dots as not supported by artifact commands
    - name: Clean base ref name
      shell: bash
      env:
          SAFE_BASE_REF_NAME: "${{ github.base_ref }}"
      run: |
        SAFE_BASE_REF_NAME=${{ env.SAFE_BASE_REF_NAME }}
        SAFE_BASE_REF_NAME=${SAFE_BASE_REF_NAME//[\/.]/}
        echo SAFE_BASE_REF_NAME=${SAFE_BASE_REF_NAME} >> $GITHUB_ENV
    - name: Download artifact
      continue-on-error: true
      id: download-artifact
      uses: dawidd6/action-download-artifact@v2.24.2
      with:
        # Optional, workflow file name or ID
        # If not specified, will be inferred from run_id (if run_id is specified), or will be the current workflow
        workflow: shopify-cli.yml
        # Optional, the status or conclusion of a completed workflow to search for
        # Can be one of a workflow conclusion:
        #   "failure", "success", "neutral", "cancelled", "skipped", "timed_out", "action_required"
        # Or a workflow status:
        #   "completed", "in_progress", "queued"
        # Use the empty string ("") to ignore status or conclusion in the search
        workflow_conclusion: success
        # Optional, will use the specified branch. Defaults to all branches
        branch: main
        # Optional, uploaded artifact name,
        # will download all artifacts if not specified
        # and extract them into respective subdirectories
        # https://github.com/actions/download-artifact#download-all-artifacts
        name: ${{ env.SAFE_BASE_REF_NAME }}--coverage-report
        # Optional, choose how to exit the action if no artifact is found
        # can be one of:
        #  "fail", "warn", "ignore"
        # default fail
        if_no_artifact_found: ignore
    - uses: ArtiomTr/jest-coverage-report-action@v2.1.2
      id: coverage
      with:
        output: report-markdown
        coverage-file: "./report.json"
        base-coverage-file: "./baseline-report.json"
        threshold: 0
    - uses: marocchino/sticky-pull-request-comment@v2.3.1
      with:
        message: ${{ steps.coverage.outputs.report }}
