# .circleci/config.yml
version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  deploy:
    docker:
      - image: cimg/node:20.5.0
    environment:
      COMMIT_URL: << pipeline.project.git_url >>/commit/<<pipeline.git.revision>>
    steps:
      - checkout
      - node/install-packages:
          with-cache: true
      - run:
          name: Install Shopify CLI
          command: npm install -g @shopify/cli
      - run:
          name: Deploy
          environment:
            # SHOPIFY_CLI_PARTNERS_TOKEN should be present as a secret
            # .env content after a deploy
            SHOPIFY_API_KEY: xxxx
          command: |
            shopify app deploy -f --source-control-url $COMMIT_URL
workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: main
