name: changeset

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: changeset-${{ github.head_ref }}
  cancel-in-progress: true

env:
  PNPM_VERSION: "7.18.1"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: ${{ env.PNPM_VERSION }}
      - name: Set Node.js
        uses: actions/setup-node@master
        with:
          node-version: '16'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Create Release Pull Request
        uses: Wandalen/wretry.action@master
        with:
          action: changesets/action@v1
          attempt_limit: 3
          attempt_delay: 2000
          with: |
            version: pnpm changeset-manifests
